--Creation of the database
DROP TABLE IF EXISTS GROCERY_ORDER;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS FEEDBACK;

--Tables
CREATE TABLE USER(
  ID_USER INTEGER IDENTITY PRIMARY KEY,
  FULL_NAME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE FEEDBACK(
  ID_FEEDBACK INTEGER IDENTITY PRIMARY KEY,
  RATE INTEGER NOT NULL,
  COMMENT CLOB NOT NULL,
  CREATED TIMESTAMP NOT NULL
);

CREATE TABLE GROCERY_ORDER(
  ID_GROCERY_ORDER INTEGER IDENTITY PRIMARY KEY,
  SHIPPING_ADDRESS CLOB,
  CREATION_DATE DATE,
  ID_USER INTEGER NOT NULL,
  ID_FEEDBACK INTEGER,
  FOREIGN KEY (ID_USER) REFERENCES USER(ID_USER),
  FOREIGN KEY (ID_FEEDBACK) REFERENCES FEEDBACK(ID_FEEDBACK)
);

--INITIAL DATA
INSERT INTO USER(FULL_NAME, EMAIL) VALUES ('Fulanito Perez', 'fulanito123@correo.com');
INSERT INTO USER(FULL_NAME, EMAIL) VALUES ('Perenganito Sanchez', 'perenganito123@correo.com');
INSERT INTO USER(FULL_NAME, EMAIL) VALUES ('Ivan Martinez','ivan123@correo.com');

INSERT INTO FEEDBACK(RATE, COMMENT, CREATED) VALUES (RAND() * 4 + 1, 'Nice product!', CURRENT_TIMESTAMP());
INSERT INTO FEEDBACK(RATE, COMMENT, CREATED) VALUES (RAND() * 4 + 1, 'Not what i was expecting' , CURRENT_TIMESTAMP());
INSERT INTO FEEDBACK(RATE, COMMENT, CREATED) VALUES (RAND() * 4 + 1, 'still waiting for my product to arrive :/', CURRENT_TIMESTAMP());
INSERT INTO FEEDBACK(RATE, COMMENT, CREATED) VALUES (RAND() * 4 + 1, 'it was a really expensive shipping ', CURRENT_TIMESTAMP());

INSERT INTO GROCERY_ORDER(SHIPPING_ADDRESS, CREATION_DATE, ID_USER, ID_FEEDBACK) VALUES ('STREET 1A #234B', CURRENT_DATE(), 1, 1);
INSERT INTO GROCERY_ORDER(SHIPPING_ADDRESS, CREATION_DATE, ID_USER, ID_FEEDBACK) VALUES ('STREET 1A #234B',CURRENT_DATE(),1,2);
INSERT INTO GROCERY_ORDER(SHIPPING_ADDRESS, CREATION_DATE, ID_USER, ID_FEEDBACK) VALUES ('AV INDEPENDENCE #3313',CURRENT_DATE(),2,3);
INSERT INTO GROCERY_ORDER(SHIPPING_ADDRESS, CREATION_DATE, ID_USER, ID_FEEDBACK) VALUES ('OLD ROAD #44',CURRENT_DATE(),3,4);
-- GROCERIES WITHOUT FEEDBACK TO WAITING TO BE FILLED
INSERT INTO GROCERY_ORDER(SHIPPING_ADDRESS, CREATION_DATE, ID_USER) VALUES ('OLD ROAD',CURRENT_DATE(),3); --4
INSERT INTO GROCERY_ORDER(SHIPPING_ADDRESS, CREATION_DATE, ID_USER) VALUES ('AV INDEPENDENCE #3313',CURRENT_DATE(),2); --5
INSERT INTO GROCERY_ORDER(SHIPPING_ADDRESS, CREATION_DATE, ID_USER) VALUES ('AV INDEPENDENCE #3313',CURRENT_DATE(),2); --6

COMMIT;